package hospital.management.system;

import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliet
 */
public class addNewPatientRecord extends javax.swing.JFrame {

    /**
     * Creates new form addNewPatientRecord
     */
    public addNewPatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        patientTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        genotypeComboBox = new javax.swing.JComboBox<>();
        bloodGroupComboBox = new javax.swing.JComboBox<>();
        ageTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        previousAilmentTextField = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/Close.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Genotype");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 98, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Any Previous Ailment");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Blood Group");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        patientTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(patientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 250, 30));

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 250, 30));

        contactTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 248, 30));

        genderComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 139, 30));

        genotypeComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genotypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "AS", "AC", "SS" }));
        genotypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genotypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(genotypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 139, 30));

        bloodGroupComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bloodGroupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        bloodGroupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(bloodGroupComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 139, 30));

        ageTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 248, 30));

        addressTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 247, 30));

        previousAilmentTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(previousAilmentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 393, 247, 30));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/save-icon--1.png"))); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient background.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
             setVisible(false);      
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void patientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
       /** String patientID = patientTextField.getText();
        String name = nameTextField.getText();
        String contactNumber = contactTextField.getText();
        String age = ageTextField.getText();
        String gender = (String)genderComboBox.getSelectedItem();
        String genotype = (String)genotypeComboBox.getSelectedItem();
        String bloodGroup = (String)bloodGroupComboBox.getSelectedItem();
        String address = addressTextField.getText();
        String previousAilment = previousAilmentTextField.getText();
        
        try{
          
          //Connection con = ConnectionProvider.getCon();
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hospitalmanagementdb","root","");
          Statement st = con.createStatement();
          st.executeUpdate("insert into patient values('"+patientID+"', '"+name+"', '"+contactNumber+"'"
                  + ", '"+age+"', '"+gender+"', '"+genotype+"'"
                          + ", '"+bloodGroup+"', '"+address+"', "
                                  + "'"+previousAilment+"')");
          JOptionPane.showMessageDialog(this,"Patient Record Successfully Added");
          //setVisible(false);
          new addNewPatientRecord().setVisible(true);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Enter All Details");
        } */
       
       
        if(patientTextField.getText().isEmpty() || nameTextField.getText().isEmpty() || 
                contactTextField.getText().isEmpty() ||  ageTextField.getText().isEmpty() || 
                addressTextField.getText().isEmpty() || previousAilmentTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing field");
        }    
        else {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hospitalmanagementdb","root","");
                PreparedStatement Add =con.prepareStatement("insert into PatientTable values(?,?,?,?,?,?,?,?,?)");
                Add.setString(1, patientTextField.getText());
                Add.setString(2, nameTextField.getText());
                Add.setString(3, contactTextField.getText());
                Add.setString(4, ageTextField.getText());
                Add.setString(5, genderComboBox.getSelectedItem().toString());
                Add.setString(6, genotypeComboBox.getSelectedItem().toString());
                Add.setString(7, bloodGroupComboBox.getSelectedItem().toString());
                Add.setString(8, addressTextField.getText());
                Add.setString(9, previousAilmentTextField.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Record Successfully Added");
                con.close();
                Clear();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Connection Error");
            }
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void genotypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genotypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genotypeComboBoxActionPerformed

    private void bloodGroupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupComboBoxActionPerformed

      private void Clear() {
        patientTextField.setText("");
        nameTextField.setText("");
        contactTextField.setText("");
        ageTextField.setText("");
        addressTextField.setText("");
        previousAilmentTextField.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewPatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JComboBox<String> bloodGroupComboBox;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JComboBox<String> genotypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField patientTextField;
    private javax.swing.JTextField previousAilmentTextField;
    // End of variables declaration//GEN-END:variables
}
