/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliet
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    
    public int i = 0;
    
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AddNewPatientRecordBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/two arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        AddNewPatientRecordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient.png"))); // NOI18N
        AddNewPatientRecordBtn.setText("Add New Patient Record");
        AddNewPatientRecordBtn.setPreferredSize(new java.awt.Dimension(205, 59));
        AddNewPatientRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewPatientRecordBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddNewPatientRecordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 215, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add diag.png"))); // NOI18N
        jButton3.setText("Add Diagnosis Information");
        jButton3.setPreferredSize(new java.awt.Dimension(215, 59));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_history1.png"))); // NOI18N
        jButton4.setText("Full Patient History");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 215, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_update_details.png"))); // NOI18N
        jButton5.setText("Update Patient Record");
        jButton5.setPreferredSize(new java.awt.Dimension(197, 59));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 327, 215, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_hospital_information.png"))); // NOI18N
        jButton6.setText("Hospital Information");
        jButton6.setPreferredSize(new java.awt.Dimension(185, 59));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 404, 215, -1));

        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/exit.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setPreferredSize(new java.awt.Dimension(121, 59));
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 481, 215, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(i==0) {
            AddNewPatientRecordBtn.setLocation(90,30);
            jButton3.setLocation(333,30);
            jButton4.setLocation(576,30);
            jButton5.setLocation(819,30);
            jButton6.setLocation(1062,30);
            LogoutBtn.setLocation(1062,89);
            i=1;
        }
        else {
            AddNewPatientRecordBtn.setLocation(10,107);
            jButton3.setLocation(10,184);
            jButton4.setLocation(10,261);
            jButton5.setLocation(10,338);
            jButton6.setLocation(10,415);
            LogoutBtn.setLocation(10,490);
            i=0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          new addDiagnosisInformation().setVisible(true);
            //this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new fullPatientHistory().setVisible(true);
            //this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Want to exit the system?", "Select",
                JOptionPane.YES_NO_OPTION);
        if(a==0) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void AddNewPatientRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPatientRecordBtnActionPerformed
        
        new addNewPatientRecord().setVisible(true);
            //this.dispose();
    }//GEN-LAST:event_AddNewPatientRecordBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        new updatePatientRecord().setVisible(true);
            //this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new hospitalInformation().setVisible(true);
            //this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewPatientRecordBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
