package hospital.management.system;

import java.sql.DriverManager;
import java.sql.*;
//import Project.ConnectionProvider;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Juliet
 */
public class updatePatientRecord extends javax.swing.JFrame {

    /**
     * Creates new form updatePatientRecord
     */
    public updatePatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        previousAilmentTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        ageTextField1 = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        genotypeTextField = new javax.swing.JTextField();
        bloodGroupTextField = new javax.swing.JTextField();
        ageTextField2 = new javax.swing.JTextField();
        ageTextField3 = new javax.swing.JTextField();
        ageTextField4 = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        genotypeTF = new javax.swing.JTextField();
        bloodGroupTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Genotype");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Blood Group");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Any Previous Ailment");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 246, -1));

        idTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 246, -1));

        numberTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(numberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 246, -1));

        previousAilmentTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        previousAilmentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousAilmentTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(previousAilmentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 246, -1));

        addressTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 246, -1));

        ageTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/search.png"))); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/save-icon--1.png"))); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/Close.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 107, -1));

        ageTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(ageTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        genderTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        genotypeTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genotypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genotypeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genotypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        bloodGroupTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bloodGroupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        ageTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(ageTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        ageTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(ageTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        ageTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(ageTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 246, -1));

        genderTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genderTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTFActionPerformed(evt);
            }
        });
        getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 250, -1));

        genotypeTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genotypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genotypeTFActionPerformed(evt);
            }
        });
        getContentPane().add(genotypeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 250, -1));

        bloodGroupTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bloodGroupTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTFActionPerformed(evt);
            }
        });
        getContentPane().add(bloodGroupTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 250, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextFieldActionPerformed

    private void previousAilmentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousAilmentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousAilmentTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        
        String patientID = idTextField.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hospitalmanagementdb","root","");
            Statement st = con.createStatement(); 
            ResultSet rs = st.executeQuery("select * from PatientTable where PatientID ='"+patientID+"'");
            if(rs.next()) {
                nameTextField.setText(rs.getString(2));
                numberTextField.setText(rs.getString(3));
                ageTextField.setText(rs.getString(4));
                genderTF.setText(rs.getString(5));
                genotypeTF.setText(rs.getString(6));
                bloodGroupTF.setText(rs.getString(7));
                addressTextField.setText(rs.getString(8));
                previousAilmentTextField.setText(rs.getString(9));
                idTextField.setEditable(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "Patient ID Does Not Exist");
            }
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Connection Error");
         }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ageTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextField1ActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void genotypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genotypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genotypeTextFieldActionPerformed

    private void bloodGroupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupTextFieldActionPerformed

    private void ageTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextField2ActionPerformed

    private void ageTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextField3ActionPerformed

    private void ageTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextField4ActionPerformed

    private void genderTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTFActionPerformed

    private void genotypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genotypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genotypeTFActionPerformed

    private void bloodGroupTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupTFActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        
        String patientID = idTextField.getText();
        String name = nameTextField.getText();
        String contactNumber = numberTextField.getText();
        String age = ageTextField.getText();
        String gender = genderTF.getText();
        String genotype = genotypeTF.getText();
        String bloodGroup = bloodGroupTF.getText();
        String address = addressTextField.getText();
        String previousAilment = previousAilmentTextField.getText();
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hospitalmanagementdb","root","");
            Statement st = con.createStatement(); 
            st.executeUpdate("update PatientTable set Name ='"+name+"', ContactNumber ='"+contactNumber+"',"
                    + "Age ='"+age+"', Gender ='"+gender+"', Genotype ='"+genotype+"',"
                            + "BloodGroup ='"+bloodGroup+"', Address ='"+address+"', "
                                    + "AnyPreviousAilment ='"+previousAilment+"' where PatientID ='"+patientID+"'");
            JOptionPane.showMessageDialog(this, "Record Successfully Updated");
            setVisible(false);
            new updatePatientRecord().setVisible(true);
        }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Please enter data in correct format");
         }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatePatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField ageTextField1;
    private javax.swing.JTextField ageTextField2;
    private javax.swing.JTextField ageTextField3;
    private javax.swing.JTextField ageTextField4;
    private javax.swing.JTextField bloodGroupTF;
    private javax.swing.JTextField bloodGroupTextField;
    private javax.swing.JTextField genderTF;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField genotypeTF;
    private javax.swing.JTextField genotypeTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JTextField previousAilmentTextField;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
